// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKAgODVs8rWMU7Uy6eovzdHTAd-UHN-Gs',
    appId: '1:1037830621063:web:4d6cd8e178607c4b40b522',
    messagingSenderId: '1037830621063',
    projectId: 'zini-chat-new-new',
    authDomain: 'zini-chat-new-new.firebaseapp.com',
    storageBucket: 'zini-chat-new-new.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ1CkY6Rj0mXywMA4gl-Oazt1AEFDXz5s',
    appId: '1:1037830621063:android:cde014c9d6769d4040b522',
    messagingSenderId: '1037830621063',
    projectId: 'zini-chat-new-new',
    storageBucket: 'zini-chat-new-new.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAZ8TO2OOO8qDA7cEDBvesRF3SFNrMWOc',
    appId: '1:1037830621063:ios:86cd3e774dd596be40b522',
    messagingSenderId: '1037830621063',
    projectId: 'zini-chat-new-new',
    storageBucket: 'zini-chat-new-new.appspot.com',
    iosBundleId: 'com.example.ziniChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSHxIgvK-b5S4XIgEWzl2TnCYydgVccys',
    appId: '1:531151449604:ios:28e6d2133e49b9fcde0f51',
    messagingSenderId: '531151449604',
    projectId: 'zini-chat-2024',
    storageBucket: 'zini-chat-2024.appspot.com',
    iosBundleId: 'com.example.ziniChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCId1Xv-zLRUtKeGG_MJOf94Po2KzsYJNA',
    appId: '1:531151449604:web:62ad90c3b1395dcade0f51',
    messagingSenderId: '531151449604',
    projectId: 'zini-chat-2024',
    authDomain: 'zini-chat-2024.firebaseapp.com',
    storageBucket: 'zini-chat-2024.appspot.com',
  );
}